# Generated by Django 5.1 on 2024-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin_cart_product_user_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6)),
                ('card_no', models.CharField(max_length=15)),
                ('paid', models.CharField(max_length=20)),
            ],
        ),
    ]
